[package]
name = "serve"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
hello = { path = "../hello" }
hyper = { workspace = true }
log = { workspace = true }
pretty_env_logger = { workspace = true }
