[package]
name = "version"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
vergen-git2 = { workspace = true }